# Generic ARM bare-metal toolchain for GCC
set(CMAKE_SYSTEM_NAME Generic)
set(CMAKE_SYSTEM_PROCESSOR arm)
set(CMAKE_TRY_COMPILE_TARGET_TYPE STATIC_LIBRARY)

set(ARM_NONE_EABI arm-none-eabi)
set(CMAKE_C_COMPILER   ${ARM_NONE_EABI}-gcc)
set(CMAKE_CXX_COMPILER ${ARM_NONE_EABI}-g++)
set(CMAKE_ASM_COMPILER ${ARM_NONE_EABI}-gcc)
set(CMAKE_AR           ${ARM_NONE_EABI}-ar)
set(CMAKE_OBJCOPY      ${ARM_NONE_EABI}-objcopy)
set(CMAKE_OBJDUMP      ${ARM_NONE_EABI}-objdump)
set(CMAKE_SIZE         ${ARM_NONE_EABI}-size)

set(CMAKE_C_STANDARD 17)
set(CMAKE_CXX_STANDARD 20)
set(CMAKE_CXX_STANDARD_REQUIRED ON)
